server:
  port: 8004

spring:
  application:
    name: order-openfeign
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        username: nacos
        password: nacos
        namespace: public

logging:
  level:
    com.mfw.order.feign: debug
